/** @format */

import React from 'react';
import localFont from 'next/font/local';

import Grid from './grid';

import '@/styles/globals.css';

const inter = localFont({
  src: './assets/fonts/Inter.woff2',
  variable: '--font-inter',
  weight: '100 900',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const showGrid = process.env.REACT_APP_SHOW_GRID === 'true';

  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased dark:bg-black dark:text-white bg-white text-black`}
      >
        {showGrid && <Grid />}
        {children}
      </body>
    </html>
  );
}
